--- 
- name: "Configuring web server"
  hosts: webservers
  become: true

  tasks:
  - name: Install the latest version of Apache
    ansible.builtin.yum:
      name: httpd
      state: latest

  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: httpd
      state: started

  - name: Install the latest version of git
    ansible.builtin.yum:
      name: git
      state: latest

  - name: Clone a repo with separate git directory
    ansible.builtin.git:
      repo: https://github.com/fakure2020/static-ecomarce-project.git
      dest: /home/ansible/ecommerce-static-application

  - name: Copy project files into dedicated directory
    ansible.builtin.copy:
      src: //home/ansible/ecommerce-static-application
      dest: /var/www/html/
      remote_src: yes